version: '3.8'
services:
  dev-game-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=ultra_game
    networks:
      - ultra-game-net
networks:
  ultra-game-net:
